name: Docker Build

on:
  push:
    branches: [ main ]
    paths:
      - 'ml-application/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ml-application/**'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./ml-application
        file: ./ml-application/Dockerfile
        tags: ml-application:latest
        load: true

